@startuml
participant ApplicationFacade

participant MeasurementSourcesFactory
participant MeasurementStoresFactory

participant MeasurementCoordinator
participant MeasurementDataStore

== Initialization ==

ApplicationFacade --> MeasurementSourcesFactory: initialize
ApplicationFacade --> MeasurementStoresFactory: initialize

ApplicationFacade --> MeasurementCoordinator : initialize
ApplicationFacade --> MeasurementDataStore : initialize

MeasurementSourcesFactory --> MeasurementCoordinator : registerSources
MeasurementStoresFactory --> MeasurementDataStore : registerStores

== Run ==

loop Each cycle
    ApplicationFacade --> MeasurementCoordinator : tick()

    loop Each MeasurementSource
        MeasurementCoordinator --> MeasurementCoordinator : updateMeasurements()
        MeasurementCoordinator --> MeasurementDataStore : store()
        
        loop Each MeasurementStore
            MeasurementDataStore --> MeasurementDataStore : store()
        end
    end
end

@enduml
