@startuml
participant ApplicationFacade

participant MeasurementCoordinator

== Initialization ==

ApplicationFacade --> MeasurementCoordinator : init
ApplicationFacade --> MeasurementCoordinator : start

== Run ==

loop Each cycle
    ApplicationFacade --> MeasurementCoordinator : tick()

    loop Each MeasurementSource
        MeasurementCoordinator --> MeasurementCoordinator : getMeasurement()
        
        loop Each MeasurementStore
            MeasurementCoordinator --> MeasurementCoordinator : notify()
        end
    end
end
@enduml