@startuml
[*] --> Init

state Init {
  [*] --> HAL_Init
  HAL_Init --> HMI_Init

  state HMI_Init {
    [*] -> Display_Init
    Display_Init -> Backlight_Init
    Backlight_Init -> Keyboard_Init
  }

  HMI_Init -->  UART_Init

  state UART_Init {
    [*] ->  Meassurement_Devices_UART_Init
    Meassurement_Devices_UART_Init -> Local_User_UART_Init
    Local_User_UART_Init -> Wifi_UART_Init
  }
  
  UART_Init -->SDCard_Init

  SDCard_Init --> Wifi_Init

}

@enduml