@startuml

package Application {
    note top of HMILayout
    1/ Based on MVC
    2/ Details TBD
    end note
    class HMILayout

    note top of DataGateway
    Has access to 
    measurement data
    end note
    class DataGateway

}

package Device {
    class DisplayBacklight
    Interface IDisplay

    class Keyboard

    class KeysDebouncer {
        -uint8_t period
    }
}

package Driver {
    interface IAmbientLightSensorDriver
    class DummyAmbientLightSensorDriver
    IAmbientLightSensorDriver <|-- DummyAmbientLightSensorDriver

    interface IDisplayBacklightDriver
    class ST7735DisplayBacklightDriver
    IDisplayBacklightDriver <|-- ST7735DisplayBacklightDriver

    class ST7735Display
    IDisplay <|-- ST7735Display

    interface IKeysDriver
    IKeysDriver <|-- KeysDriver
    class KeysDriver
}






DisplayBacklight *-- IAmbientLightSensorDriver
DisplayBacklight *-- IDisplayBacklightDriver

Keyboard *--- IKeysDriver
Keyboard *-- KeysDebouncer

HMILayout *-- IDisplay
HMILayout *-- DisplayBacklight
HMILayout *-- Keyboard
HMILayout - DataGateway

/'
enum Key_State_t {
    LOGGER_KEYBOARD_KEY_PRESS
    LOGGER_KEYBOARD_KEY_NO_PRESS
}

enum Keys_Key_Id_t {
    LOGGER_KEYBOARD_KEY_UP
    LOGGER_KEYBOARD_KEY_DOWN
    LOGGER_KEYBOARD_KEY_LEFT
    LOGGER_KEYBOARD_KEY_RIGHT
}
'/

@enduml
