@startuml

package BusinessLogic {
    class MeasurementSubject {
    }
}

package Device {
    interface IMeasurementDevice {
    }


    class PulesTransmitingDevice {
    }

    class UARTTransmitingDevice {
    }
}

package Driver {
    class GPIOCounterDevice {
    }

    interface IUARTDriver {
    }

    class UARTDriver {
    }
}


MeasurementSubject *--- PulesTransmitingDevice
MeasurementSubject *-- UARTTransmitingDevice
IMeasurementDevice <|-- PulesTransmitingDevice
IMeasurementDevice <|-- UARTTransmitingDevice

UARTTransmitingDevice -- IUARTDriver
PulesTransmitingDevice -- GPIOCounterDevice

IUARTDriver --|> UARTDriver

@enduml