name: Unit Tests

on:
  workflow_run:
    workflows: ["Build Docker"]
    types: [completed]
    branches: [main, "feature/*"]

jobs:
  unit-tests:
    name: Unit Tests (${{ matrix.name }})
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Device
            preset: unit-device

          - name: Business Logic
            preset: unit-businesslogic

          - name: Driver
            preset: unit-driver

    uses: robertgawron/hardwaredatalogger/.github/workflows/docker-postbuild-generic.yml@main
    with:
      docker_image_repo: robertgawron/hardwaredatalogger
      artifact_name: test-logs-${{ matrix.preset }}
      artifact_paths: /tmp/cmake-${{ matrix.preset }}/Testing

      run_script: |
        cmake --preset ${{ matrix.preset }}
        cmake --build --preset ${{ matrix.preset }}
        ctest --preset ${{ matrix.preset }}